In [1]:
import pandas as pd

In [7]:
df = pd.DataFrame({
    "Price" : [100,200,300]
})
print(type(df["Price"].values))
    

<class 'numpy.ndarray'>


In [2]:
import numpy as np

In [23]:
salary = [1000,2000,3000]
salary_array = np.array(salary)
new_salary_array = salary_array + 1
new_salary_array
print(salary_array.ndim)
print(salary_array[-1])
# type(salary_array)

1
3000


In [46]:
data = np.array([
    [10,1000],
    [20,2000],
    [30,3000],
    [40,4000],
    [50,5000],
    [60,6000]
])
print(data[:,1])
print(data[3:5])
print(data[2,0])
print(data.ndim)
print(data.shape)
print(data.size)

price = np.array([10,20,30])
print(price.dtype)
price2=np.array([10.2,20.2,30.2])
print(price2.dtype)

[1000 2000 3000 4000 5000 6000]
[[  40 4000]
 [  50 5000]]
30
2
(6, 2)
12
int64
float64


numbers = np.array([1,2,3,4,5])
new_number = numbers * 10
print(new_number)
new_number > 30
new_number[(new_number > 30) & (new_number < 50)] 

price = np.array([100,200,300])
quantity = np.array([1,2,3])

price * quantity

In [51]:
numbers = [1,2,3,4,5]
results = []
for num in numbers:
    results.append(num*10)
print(results)
    

[10, 20, 30, 40, 50]


In [3]:
numbers = np.array([10,20,30])
new_num = numbers + 1
print(new_num)

[11 21 31]


In [11]:
numbers = np.array([1,2,3,4,5])
new_number = numbers * 10
print(new_number)
new_number > 30
new_number[(new_number > 30) & (new_number < 50)] 

price = np.array([100,200,300])
quantity = np.array([1,2,3])
print(price.shape)
price * quantity

[10 20 30 40 50]
(3,)


array([100, 400, 900])

In [14]:
arr = np.array([1,2,3,4,5,6])
arr.shape
arr.reshape(2,3)
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
# arr2.reshape(1,6)
arr2.reshape(-1)

array([1, 2, 3, 4, 5, 6])