In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.multiclass import OneVsRestClassifier

In [2]:
df = pd.read_csv("datasets/Question2.csv")

In [3]:
df.head()

,Student,Attendance,MathScore,EnglishScore,QuizScore,MissedClasses,MathSupport,EnglishSupport,AttendanceSupport
0,Aarav,72,55,58,61,1,0,1,0
1,Sita,91,86,84,88,0,0,0,0
2,Ram,68,48,52,55,4,1,1,0
3,Anisha,94,92,89,91,0,0,0,0
4,Rohan,75,60,57,63,2,0,1,0


In [4]:
df.shape

(20, 9)

In [5]:
df.isnull().sum()

Student              0
Attendance           0
MathScore            0
EnglishScore         0
QuizScore            0
MissedClasses        0
MathSupport          0
EnglishSupport       0
AttendanceSupport    0
dtype: int64

In [11]:
X = df[["Attendance","MathScore","EnglishScore","QuizScore","MissedClasses"]]
y = df[["MathSupport", "EnglishSupport", "AttendanceSupport" ]]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
model = OneVsRestClassifier(LogisticRegression())
model.fit(X_train,y_train)
prediction = model.predict(X_test)
print(prediction)

[[1 1 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
new_student = pd.DataFrame({
    "Attendance" : [92],
    "MathScore" : [54],
    "EnglishScore" : [92],
    "QuizScore" : [42],
    "MissedClasses" : [2]
})
predict = model.predict(new_student)
predict

array([[1, 0, 0]])

In [19]:
result = pd.Series(np.where(predict[0] == 1, 'YES', 'NO'), 
                   index=["Math Support", "English Support", "Attendance Support"])

print("Student Support Prediction:\n")
print(result.to_string())

Student Support Prediction:

Math Support          YES
English Support        NO
Attendance Support     NO
